version: '3.8'

services:
  garmin-dev:
    build: .
    container_name: garmin-watchface-dev
    working_dir: /workspace/analog-face
    stdin_open: true
    tty: true
    volumes:
      # Optional: mount a volume for persistent build outputs
      - garmin-builds:/workspace/analog-face/build
      - hs_dev_mount:/mnt/hs_dev:ro
    networks:
      - garmin-dev-network
    command: tail -f /dev/null

volumes:
  garmin-builds:
    driver: local
  hs_dev_mount:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas-home.local,nolock,ro"
      device: ":/volume1/hs_dev"

networks:
  garmin-dev-network:
    driver: bridge


