version: '3.8'

services:
  garmin-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garmin-fr970-build
    tty: true
    working_dir: /workspace/analog-face
    stdin_open: true
    command: /bin/bash
    environment:
      - CIQ_HOME=/app/connectiq-sdk
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - DISPLAY=:99
    labels:
      - "description=Self contained Garmin ConnectIQ Build Environment for FR970"
      - "project=garmin-watchface"
