version: '3.8'

services:
  garmin-dev:
    build: .
    container_name: garmin-watchface-dev
    working_dir: /workspace/analog-face
    stdin_open: true
    tty: true
    command: /bin/bash
    environment:
      - CIQ_HOME=/workspace/analog-face/connectiq-sdk
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/workspace/analog-face/connectiq-sdk/bin
    volumes:
      # Optional: mount a volume for persistent build outputs
      - garmin-builds:/workspace/analog-face/build
      - hs_dev_mount:/mnt/hs_dev:rw
    networks:
      - garmin-dev-network

volumes:
  garmin-builds:
    driver: local
  hs_dev_mount:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas-home.local,nolock,rw"
      device: ":/volume1/hs_dev"

networks:
  garmin-dev-network:
    driver: bridge


