version: '3.8'

services:
  garmin-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garmin-watchface-dev
    working_dir: /workspace/analog-face
    restart: unless-stopped
    volumes:
      # Optional: mount a volume for persistent build outputs
      - garmin-builds:/workspace/analog-face/build
      - hs_dev_mount:/mnt/hs_dev:ro
    ports:
      - "6080:80"     # for browser-based GUI
    networks:
      - garmin-dev-network
    environment:
     - TZ=Europe/London
    tty: true
    command: /startup.sh
    
volumes:
  garmin-builds:
    driver: local
  hs_dev_mount:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=nas-home.local,nolock,ro"
      device: ":/volume1/hs_dev"

networks:
  garmin-dev-network:
    driver: bridge


